package com.example.Nuna.model;

public enum Genre {
    FOODIE_ADVENTURES,
    NATURE_TRAILS,
    CULTURAL_TOURS,
    EVENT_GUIDES,
    ROAD_TRIP_ROUTES,
    CITY_GUIDES,
    PHOTOGRAPHER_PARADISE,
    FAMILY_FRIENDLY,
    PET_FRIENDLY,
}
